Update forms.py
+ Couldn't pass just kwargs, yet, got an error on rx.select: TypeError: HighLevelSelect.create() missing 1 required positional argument: 'items'
+ I tried changing the name from item_list to items, and changing the position from last to first (to match the position), but it seems like select has to be treated differently. TODO